"""Generate visible chart.png and report.pdf in the current working directory.

Called by the demo loop's assets agent under ``--mock bash`` (the prompt is
executed as a shell command, so this script runs with cwd = run working dir).

These assets are meant to be *previewed in the WebUI*, so they carry real
visible content (not 1x1/empty stubs): chart.png is a 400x300 gradient chart
with a curve; report.pdf is a one-page document with a title and body text.
Both are generated with the standard library only (no PIL/reportlab).
"""
from __future__ import annotations

import struct
import zlib
from pathlib import Path


# --- PNG ---──────────────────────────────────────────────────────────────────

def _png_chunk(tag: bytes, data: bytes) -> bytes:
    return (
        struct.pack(">I", len(data))
        + tag
        + data
        + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
    )


def make_png(path: Path, width: int = 400, height: int = 300) -> None:
    """400x300 chart: horizontal blue gradient, a visible orange curve,
    and a baseline — clearly visible when previewed."""
    rows = bytearray()
    for y in range(height):
        rows.append(0)  # filter type: none
        for x in range(width):
            # horizontal gradient: blue-ish background
            r = 20 + (x * 180) // width
            g = 60 + (y * 120) // height
            b = 220 - (x * 60) // width
            # orange curve: y = height - 40 - 120*sin(2pi x / width)
            import math

            curve_y = height - 40 - int(120 * math.sin(2 * math.pi * x / width))
            if abs(y - curve_y) <= 2:
                r, g, b = 255, 140, 0
            # baseline at bottom
            if y >= height - 6:
                r, g, b = 40, 40, 40
            rows.extend((r, g, b))

    sig = b"\x89PNG\r\n\x1a\n"
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    idat = zlib.compress(bytes(rows), 6)
    path.write_bytes(
        sig
        + _png_chunk(b"IHDR", ihdr)
        + _png_chunk(b"IDAT", idat)
        + _png_chunk(b"IEND", b"")
    )


# --- PDF ---──────────────────────────────────────────────────────────────────

def _pdf_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def make_pdf(path: Path) -> None:
    """One-page PDF with a title, body text and a footer — visible content,
    valid xref so viewers render it (not an empty MediaBox)."""
    title = "Demo Report (loopflow)"
    body = (
        "This PDF was generated by the loopflow demo loop under mock bash. "
        "It verifies the WebUI raw preview (AC-033) end-to-end. "
        "Demo report body text."
    )
    footer = "Generated by loopflow demo loop (BL-057/058)"

    objects: list[bytes] = []
    objects.append(b"<< /Type /Catalog /Pages 2 0 R >>")                       # 1
    objects.append(b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>")               # 2
    objects.append(                                                             # 3
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        b"/Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>"
    )
    objects.append(                                                             # 4
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"
    )
    content = (
        "BT /F1 24 Tf 72 700 Td (" + _pdf_escape(title) + ") Tj ET\n"
        "BT /F1 12 Tf 72 660 Td (" + _pdf_escape(body) + ") Tj ET\n"
        "BT /F1 10 Tf 72 60 Td (" + _pdf_escape(footer) + ") Tj ET\n"
    ).encode("latin-1")
    objects.append(b"<< /Length " + str(len(content)).encode() + b" >>\nstream\n" + content + b"endstream")  # 5

    out = bytearray(b"%PDF-1.4\n")
    offsets = [0]
    for i, obj in enumerate(objects, start=1):
        offsets.append(len(out))
        out.extend(f"{i} 0 obj\n".encode())
        out.extend(obj)
        out.extend(b"\nendobj\n")
    xref_pos = len(out)
    out.extend(f"xref\n0 {len(objects) + 1}\n".encode())
    out.extend(b"0000000000 65535 f \n")
    for off in offsets[1:]:
        out.extend(f"{off:010d} 00000 n \n".encode())
    out.extend(
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\n"
        f"startxref\n{xref_pos}\n%%EOF\n".encode()
    )
    path.write_bytes(bytes(out))


def main() -> int:
    make_png(Path("chart.png"))
    make_pdf(Path("report.pdf"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
