import type { Backend, LoopDetail, LoopSummary, RunDetail, RunSummary } from '../types';

export const runs: RunSummary[] = [
  { run_id: 'run-live', working_directory: 'lf_tmp-review-workspace', loop: 'review-loop', status: 'running', created: '2026-07-18T22:00:00Z', started_at: '2026-07-18T22:00:00Z', finished_at: null, updated_at: '2026-07-18T22:00:03Z', duration_ms: 3200, iteration_count: 1, error_summary: null, parse_error: null, allowed_actions: ['stop'] },
  { run_id: 'run-waiting', working_directory: 'lf_tmp-review-workspace', loop: 'review-loop', status: 'waiting_input', created: '2026-07-18T22:00:00Z', started_at: '2026-07-18T22:00:00Z', finished_at: null, updated_at: '2026-07-18T22:00:03Z', duration_ms: 3200, iteration_count: 1, error_summary: null, parse_error: null, allowed_actions: ['respond', 'stop'] },
  { run_id: 'run-failed', working_directory: 'lf_tmp-review-workspace', loop: 'review-loop', status: 'failed', created: '2026-07-18T21:00:00Z', started_at: '2026-07-18T21:00:00Z', finished_at: '2026-07-18T21:02:00Z', updated_at: '2026-07-18T21:02:00Z', duration_ms: 120000, iteration_count: 0, error_summary: 'Agent failed', error_category: 'quota', parse_error: null, allowed_actions: ['recover_retry', 'recover_continue', 'rerun'] },
  { run_id: 'run-cancelled', working_directory: 'lf_tmp-review-workspace', loop: 'review-loop', status: 'cancelled', created: '2026-07-18T20:00:00Z', started_at: '2026-07-18T20:00:00Z', finished_at: '2026-07-18T20:01:00Z', updated_at: '2026-07-18T20:01:00Z', duration_ms: 60000, iteration_count: 0, error_summary: null, parse_error: null, allowed_actions: ['recover_retry', 'respond', 'rerun'] },
  { run_id: 'run-broken', working_directory: 'lf_tmp-review-workspace', loop: null, status: 'unreadable', created: null, started_at: null, finished_at: null, updated_at: null, duration_ms: null, iteration_count: 0, error_summary: null, parse_error: 'line 1, column 2: broken', allowed_actions: [] },
  { run_id: 'run-stale', working_directory: 'lf_tmp-review-workspace', loop: 'review-loop', status: 'stale', created: '2026-07-18T22:00:00Z', started_at: '2026-07-18T22:00:00Z', finished_at: null, updated_at: '2026-07-18T22:00:03Z', duration_ms: 3200, iteration_count: 0, error_summary: null, parse_error: null, allowed_actions: ['reconcile'], stale_since: '2026-07-18T22:00:01Z', stale_grace_remaining_seconds: 82800 },
];

export const detail: RunDetail = {
  ...runs[0], args: {}, state: { attempt: 2 }, working_directory: '/tmp/run-live',
  agent_graph: { nodes: [{ id: 'call-plan', label: 'plan', agent_def: 'planner', status: 'done' }, { id: 'call-a', label: 'reviewer', agent_def: 'reviewer', status: 'running' }], edges: [{ from: 'call-plan', to: 'call-a', kind: 'sequential' }], current: 'call-a' },
  calls: [{ call_id: 'call-plan', session: 'wf-plan', status: 'done', started_at: null, finished_at: null, exit_code: 0, backend: 'kimi', model: null }, { call_id: 'call-a', session: 'wf-review-a', status: 'running', started_at: null, finished_at: null, exit_code: null, backend: 'codex', model: 'gpt-5' }],
  unattributed_count: 0, malformed_count: 0,
  interventions: [],
  events: [{ version: 2, event_id: 1, type: 'agent_start', ts: '2026-07-18T22:00:02Z', call_id: 'call-a', payload: { backend: 'codex' } }, { version: 2, event_id: 2, type: 'agent_message', ts: '2026-07-18T22:00:03Z', call_id: 'call-a', payload: { session: 'wf-review-a', content: 'Reviewing **workflow output** now.' } }],
  unattributed: [], malformed: [],
};

export const loopSummary: LoopSummary = { name: 'review-loop', description: 'Review and fix changes', agent_count: 1, triggers: [], valid: true, error_summary: null };
export const loopDetail: LoopDetail = { name: 'review-loop', description: 'Review and fix changes', valid: true, error_summary: null, triggers: [], resources: [], environment: null, files: [{ path: 'loop.md', media_type: 'text/markdown', size: 90, previewable: true }, { path: 'workflow.py', media_type: 'text/x-python', size: 120, previewable: true }, { path: 'binary.bin', media_type: null, size: 12, previewable: false }], agents: [{ name: 'reviewer', description: 'Reviews changes', path: 'agents/reviewer.md' }], runs: [runs[1]] };
export const backends: Backend[] = [{ name: 'codex', status: 'available', reason: null, cli_path: '/usr/bin/codex', version: '1.0.0', transport: 'cli', capabilities: { native_goal: true, structured_output: true, native_skills: false, resume_session: true, durable_session_id: true }, diagnosed_at: null }, { name: 'kimi', status: 'missing', reason: 'cli_not_found', cli_path: null, version: null, transport: 'cli', capabilities: { native_goal: false, resume_session: false, durable_session_id: false }, diagnosed_at: null }];